db.url=jdbc:sqlserver://14.225.217.109;databaseName=PureNut_DB;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=TOP1@iyounguru!
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Email (SMTP Gmail)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=dodangkhoa907@gmail.com
mail.smtp.password=qhbh kqkg xwxd ugwm

# PayOS
payos.client_id=bf2796c7-6b19-4eed-a1b9-7cc324cc24f9
payos.api_key=d6072c66-879c-47a1-8703-ba07e6347cce
payos.checksum_key=763aa74cc6c96a055d90ca6deede470dc2f2520f77589ef672f152710163b679